# Generated by Django 3.1.1 on 2020-09-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='university_id',
        ),
    ]
